### ISSUE TITLE
Send test token fails

### ISSUE THREAD

**Issue by rabinvg** [bitcoindevkit/BDKSwiftExampleWallet#125]
**Describe the bug**
I tried sending 10000 test tokens to an address, it keeps throwing an error.

![Simulator Screenshot - iPhone 11 Pro Max - 2024-02-16 at 10 19 41](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/assets/131969426/1e565c6f-e45a-4a8f-9f13-745540aa55a7)

**Comment by reez** [comment]
Thanks for opening up this Issue! 

Do you mind seeing if the change #126 resolves your issue? (You may want to do the wallet setup fresh again just to make things easier?)

And I also want to note that the code in this Example Wallet supports [BIP-86](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/tree/main?tab=readme-ov-file#wallet) [at the moment](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/blob/a8c19467139c4abd681720cc4f6b193d0f07c9b1/BDKSwiftExampleWallet/Service/BDK%20Service/BDKService.swift#L89) but if you want BIP-84 you can just replace the couple spots that use BIP-86 with BIP-84.

Let me know how it goes whenever you get a chance to test it out that small change, appreciated!

**Comment by rabinvg** [comment]
Hello @reez. Thanks for the quick fix. It works now.  🎊  🎊
