### ISSUE TITLE
suggestion: rename "Output" list to "Unspent"

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/BDKSwiftExampleWallet#200]
**Is your feature request related to a problem? Please describe.**

The list of UTXOs is currently called "Output" but that sounds to me like coins that have left my wallet instead of the ones I am able to spend. 

**Describe the solution you'd like**

I think a better name for this screen would be "Unspent" since these are the "coins" in my wallet that I have available to spend.

**Describe alternatives you've considered**

Technically these are UTXOs but I think "Unspent" is the more important part of this acronym. 

**Additional context**

**Comment by reez** [comment]
THANK YOU! Great feedback, will fix

**Comment by reez** [comment]
by the way if you have an suggestions for the "Unspent" screen let me know, right now I'm just showing `txid` and `out` but obviously I could show different/more important items
